# Generated by Django 2.2.5 on 2021-11-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favouriteBookGenre',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteBookGenre', to='users.Category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favouriteMovieGenre',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteMovieGenre', to='users.Category'),
        ),
    ]
