# Generated by Django 2.2.5 on 2021-11-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211130_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='favouriteBookGenre',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteBookGenre', to='users.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favouriteMovieGenre',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteMovieGenre', to='users.Category'),
        ),
    ]
