# Generated by Django 2.2.5 on 2021-12-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(blank=True, choices=[('Common', (('action', 'Action'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('mystery', 'Mystery'))), ('Movie', (('comedy', 'Comedy'), ('drama', 'Drama'), ('romance', 'Romance'), ('thriller', 'Thriller'))), ('Book', (('adventure', 'Adventure'), ('classics', 'Classics'), ('comicBook', 'Comic Book'), ('detective', 'Dectective'), ('historical', 'Historical Fiction'), ('literary', 'Literary Fiction')))], max_length=20)),
                ('sort', models.CharField(blank=True, choices=[('book', 'Book'), ('movie', 'Movie')], max_length=5)),
            ],
            options={
                'unique_together': {('genre', 'sort')},
            },
        ),
    ]
